### ISSUE TITLE
[i3run] moving window from scratchpad returns you on previous selected workspace

### ISSUE THREAD

**Issue by socrates-XXI** [budlabs/i3ass#161]
I don't know if this is really a big deal, but I think you should know, that when you have this option in i3 config enabled:

`workspace_auto_back_and_forth yes`

i3run with --summon or without make i3 do that back_and_forth thing, so it (option or i3run scratchpad function) becomes unusable. Anyway, I just disabled back_and_forth option and it works great. Thank you so much for your stuff!

**Comment by budRich** [comment]
@socrates-XXL, thanks for bringing this up! 
I had completely forgotten about it, because i remember having this issue myself and, just as you I disabled back_and_forth, and, forgot about it.  

I took a quick look at the i3 user guide and:  
```
workspace [--no-auto-back-and-forth] <name>
workspace [--no-auto-back-and-forth] number <name>
```

I think if I add `--no-auto-back-and-forth` to all workspace operations this issue will be no more!
