### ISSUE TITLE
i3run, giving chrome a new instance/class name

### ISSUE THREAD

**Issue by alajmo** [budlabs/i3ass#164]
Hi, first of all, great software, really helpful!

So, I'm having some issues with creating a duplicate google chrome window using i3run. My setup is as follows:

workspace: 1 (here I have my terminal)
workspace: 2 (here I have a google chrome instance)

What I want to achieve is to press `$mod+g` to bring up google-chrome instance on workspace 1, leaving the other google-chrome instance on workspace 2 as it is.

It works well when I use the `st` terminal as I can give it a `-name` property for instance when I'm bringing up `htop`, but google-chrome doesn't have any `-name` flag.

The command I run is:

```
bindsym $mod+g exec --no-startup-id i3run --summon --class chrome-quick --instance chrome-quick -- google-chrome
```

This command always creates a new window (as it should since it can't find a window with class/instance chrome-quick). If I instead use

```
bindsym $mod+g exec --no-startup-id i3run --summon --class chrome-quick --instance chrome-quick  --rename-instance google-chrome --rename-class Google-chrome -- google-chrome
```
it brings the google-chrome instance from workspace 2 to workspace 1 (and renames it to chrome-quick), which I don't want.

Any idea how I can solve this?

**Comment by budRich** [comment]
Hello alajmo, thanks for reporting this!

i3run is actually working as expected here,   
`bindsym $mod+g exec --no-startup-id i3run --summon --class chrome-quick --instance chrome-quick  --rename-instance google-chrome --rename-class Google-chrome -- google-chrome`  
renames the first found instance **Google-chrome** to **chrome-quick**. 

your first keybinding example:   
`bindsym $mod+g exec --no-startup-id i3run --summon --class chrome-quick --instance chrome-quick -- google-chrome`  
Is actually wrong. But i see now that is impossible for you to know since I have forgot to add to the wiki/manpage:  
>when using criterias and a command with i3run. The command **must** result in a window that matches the criteria. Otherwise, i3run will get stuck in a loop (this is not a super big deal, but weird stuff can happen) waiting for a window matching the criteria.  

And as you pointed out, the first command, will not rename windows or anything, just spawn a window with class **Google-chrome**. The second command will not launch a new window because the target to rename already exist, and it renames and focuses that target.

So what you need to do is rename both windows. If the first command did this instead:  

`i3run --summon --class chrome-quick1 --rename Google-chrome -- google-chrome`  
(there isn't really any reason to rename both class/instance, it can actually be useful  to leave one as default).

And the next command be:  
`i3run --summon --class chrome-quick2 --rename Google-chrome -- google-chrome`  

But I am a bit confused, since you post two different commands, but with the same bindsym (`ctrl+g`), it is however possible (with the next release of i3ass) to do something like this:  

`bindsym $mod+g exec --no-startup-id i3run --class "chrome-quick$(i3get -r w)" --rename Google-chrome -- google-chrome`  

This will automatically append the current workspace number to `chrome-quick`. But as i noted and it will **NOT** work correctly till the **next release** of i3ass, because this exposed a bug for me, that the wrong workspace number is reported if the current workspace is empty. So big thank you for that (i have already fixed, it, just need to tidy up the release, will try to ship it today).  

However, this is probably not a good idea, to create chrome windows for each workspace. If you would manage to send one of those windows to the scratch pad, and later destroy the workspace (i3 automatically removes empty unfocused workspaces), it is not good. So my final suggestion is to write a simple script, and launch chrome with that:  

in `.config/i3/config`:  
`bindsym $mod+g exec --no-startup-id quickchrome`  

`quickchrome` (needs to be executable (`chmod +x`) and in your **$PATH** :  
```bash
#!/usr/bin/env bash

# the "chrome instance" is located on 2
chrome_workspace_main=2

# new chrome instances are allowed on workspace 1 and 3
chrome_workspaces_new=(1 3)

current_workspace=$(i3get -r w)

# this loop checks if the current workspace is in chrome_workspaces_new (1 or 3)
# and not the main workspace (2) if it is, exec will fork the scripts process and start
for ws in "${chrome_workspaces_new[@]}" ; do
  ((current_workspace = ws && ws != chrome_workspace_main)) && {
    exec i3run --class "quick-chrome$ws" --rename Google-chrome -- google-chrome
  }
done

# if the workspace was not matched in the loop (its not 1 or 3) we focus or create
# a chrome window with the class "quick-chrome-main" 
exec i3run --class "quick-chrome-main" --rename Google-chrome -- google-chrome
```

But I see now as i was writing this, that you found another way. Anyways, big thanks for this report, it made me fix a bug and realize i need to clarify the docs.

Happy tiling! // bud

**Comment by alajmo** [comment]
cheers for the quick response and code snippet.

Just to clarify, I only want to launch a quick chrome window (doesn't matter which workspace) (`mod + g`). The other chrome instance is not launched with i3run, but launched on i3 startup `exec exec --no-startup-id google-chrome`. Unfortunately, if it started with `google-chrome --class="dedicated"`, all subsequent chrome instances get the same class, no matter if I start them with another, but this is a bug with chrome, not i3run.

I settled for:

```
bindsym $mod+g exec i3run --class "quick-chrome" --rename Google-chrome -- google-chrome
```

The only issue is when I first start `mod+g`, the dedicated chrome switches from workspace from 2 to 1, but then if I move it back to 2, the subsequent `mod+g` don't affect it. I can see via `xprop` that the correct classes are set 

```
quick chrome: WM_CLASS(STRING) = "google-chrome", "quick-chrome"
dedicated chrome: WM_CLASS(STRING) = "google-chrome", "Google-chrome"
```

At least now I get to keep the same data_dir so the browser history is shared. I will try the next release and see if I can remove the initial issue (with switching the chrome instance back to workspace 2).
