### ISSUE TITLE
i3aas dependency issue with  4.22-2

### ISSUE THREAD

**Issue by gdane195** [budlabs/i3ass#178]
❯ yay -Suuyy
:: Synchronizing package databases...
 core                                   152.6 KiB   248 KiB/s 00:01 [######################################] 100%
 extra                                 1732.1 KiB  2.48 MiB/s 00:01 [######################################] 100%
 community                                7.2 MiB  7.91 MiB/s 00:01 [######################################] 100%
 blackarch                                3.7 MiB  2.48 MiB/s 00:01 [######################################] 100%
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...
:: i3-wm and i3ass are in conflict (i3-gaps). Remove i3ass? [y/N]

I have 4.21-1 installed!

**Comment by budRich** [comment]
thanks for reporting this! I think this is what is happening. I added i3-gaps as a conflict of i3ass (because i3ass had some problems with i3gaps). Now with gaps merged in i3 4.22, and i3-gaps being merged/replaced by normal i3, i think arch/aur has just made it so that all packages depending/in conflict with i3-ass is now depending/in conflict with i3.  

This is actually a good thing. I think all that is needed is to remove the i3-gaps conflict (afaik there are no issues using i3ass with i3v4.22, even with gaps enabled) in the AUR PKGBUILD.

I don't use Arch/AUR myself anymore, and in a way it is not optimal that i am the maintainer of the AUR package... But i will try to update it later today.

**Comment by budRich** [comment]
I updated the PKGBUILD on aur now. I hope it works. btw, I use Arch (again :)
