### ISSUE TITLE
[i3fyra] --move CONTAINER, does not create containers

### ISSUE THREAD

**Issue by budRich** [budlabs/i3ass#183]
this was originally mentioned by @1ntronaut in #180 .

And the issue is what it says in the title, if the layout is "A" the command `i3fyra --move B` should create B and move the current window there. `i3viswiz --move B` seems to work fine though...

**Comment by budRich** [comment]
@1ntronaut , i am not able to reproduce this on my personal configuration or with the [wiki config](https://github.com/budlabs/i3ass/wiki/i3-config-example)

**Comment by 1ntronaut** [comment]
Hi @budRich ,

Two (became 3) things I'd like to address two things here. I'm making separate issues.
- 1) The issue as stated above is for me not-reproducable as well, however my personal setup is so that it won't allow me to create/assign i3fyra's 'virtual containers ABCD' on i3 startup or whatever. `i3fyra --move A|B|C|D` still does't create containers for me, without having the virtual containers initialized first through
After checking... i3viswiz does not even have a `--move` flag. I wasn't using `i3viswiz --move B`, but rather `i3viswiz move up|left|down|right` and  `i3fyra --move CONTAINER`. 
It seems like a stupid error on my behalf (which it is, in retrospect), my bad, but this'll probably prelude the following:
- 2) I found out that i3viswiz does accept some (I suppose) non-intended input. It seems i3viswiz will accept any amount of arguments, as long as the last argument is any of `u|l|d|r|up|left|down|right`. 
- 2.5) During testing, I found out more:  Not only this, but i3viswiz will accept ANY amount of arguments as long as the last of its arguments begins with any of `u|l|d|r|up|left|down|right`
- 3) This might be a new issue, minor or not, but looking at my i3config, I seem to use i3viswiz to focus; and only seem to use `i3Kornhe move` to actually MOVE my windows across containers. But: it does also exhibit some of the same behaviour i3viswiz does.
