### ISSUE TITLE
i3viswiz with i3-gaps

### ISSUE THREAD

**Issue by vn-ki** [budlabs/i3ass#20]
Let me start by saying i3viswiz is awesome. But sadly it doesn't work well with i3 gaps.

My problem is when the layout is like this
```
__________________
|        |       |
|        |   B   |
|   A    |-------|
|        |   C   |
|________|_______|
```

I can switch from B to A and C to A, but I can't switch from A to B.

I think this is because viswiz focus from the middle of A, but it only see gaps there because I have gaps turned on.

I think the script should gracefully fallback a few pixels up or down depending whether it can focus successfully or not.

Thank you. You're youtube channel is awesome too.

**Comment by budRich** [comment]
Hi vn-ki, thanks for the report. I don't use gaps myself, and this issue was something i hadn't thought of, i will try to fix it. And if i remember right, i had problems even without gaps if the target ended up exactly in the middle. I think it will get solved if i add the *gapsize* (that can be set with the `-g` option) to distort the center:  

example, screen width 1600, height 800, same layout as your example, all splits 50%, gapsize default (5px) shifting focus to the right while being in container A:  

current behaviour:  
x:((1600/2)+1+5), y: ((800/2)+1)   --- x806 , y401   

i think this will work:  (adding gap in both directions)
x:((1600/2)+1+5), y: ((800/2)+1+5)   --- x806 , y406   

Thanks for testing script, and watching the channel. I have lots of stuff in the pipe, both scripts
and video content, stay tuned and happy tiling!

**Comment by budRich** [comment]
i think this issue will not be as frequent in the latest release, i will work more on this and add some sort of *try again* function that will move the target once more, but it will hopefully already be much less frequent. 

The new release is available both on github and AUR.

**Comment by vn-ki** [comment]
Wow. You are fast.

It works now. The bottom one is focus always. I hope there is a way to change that. Anyway this is way better than i3's native functionality. Thanks.

**Comment by budRich** [comment]
well, it only adds to the y axis (or the x axis if the movement is u/d), and there is currently no option to change that, but when i think about it, the top container is probably more often what one would like, it's an easy fix.  

I am fast because i have spent 10 000 hours perfecting and optimizing my workflow, which have made all my work consist of optimizing my workflow to optimize my workflow :) rice4lyfe ftw
