### ISSUE TITLE
i3get command can not parse regular expression

### ISSUE THREAD

**Issue by henryzxb** [budlabs/i3ass#211]
open thunar with class "Thunar" in the background, then try to use command 
"i3get --class 'Thunar$' --print d"  to get thunar windowid, but get nothing. is this a bug about regular expression?

OS: Archlinux
i3 version 4.23 © 2009 Michael Stapelberg and contributors
i3ass - version: 2023.08.19.1
updated: 2023-08-19 by budRich

**Comment by budRich** [comment]
Thanks for reporting this!

Yeah, regex search was not enabled for class, instance and some other properties.

---

I see you run Arch btw  
I have stopped maintaining the i3ass AUR packages, because AUR/Arch community sucks . I have planned selfhosting my own repo, but till then you better build from source. i3ass-git should also work fine to get the bleeding edge version. Just a heads up.
