### ISSUE TITLE
[i3Kornhe] Restore original window title when exiting size / move mode

### ISSUE THREAD

**Issue by lukewang1024** [budlabs/i3ass#29]
First of all, thanks for sharing your workflow to the community. Great work indeed.

There is a minor improvement suggestion for i3Kornhe:

When entering the size / move modes, it may save the latest window title somewhere, so that when quitting modes the original window title could be restored. Currently the touched windows will be left with "SIZE" as title, which could be confusing sometimes.

**Comment by budRich** [comment]
Thanks for a good issue report. 

I know exactly what you mean and how to fix this. I haven't noticed it myself because i use custom title_format for all windows (and title_format is remembered).  

I will try to fix this right away.  

I can also recommend using custom title_format if you use i3fyra, since tabs usually get too small to fit most normal default window titles.

**Comment by budRich** [comment]
this should be fixed in the latest release.
thanks again for the excellent issue and: Happy Tiling (and floating i guess ;)
