### ISSUE TITLE
[i3list] doesnt do type for target window at the moment 

### ISSUE THREAD

**Issue by APotOfSoup** [budlabs/i3ass#46]
Currently in your repo i3list has what I believe to be a bug.
`  if (floats ~ /on$/) 
    window[type]["AWF"]=1 
  else 
    window[type]["AWF"]=0`

This caused some problems with i3run setting a i3var  for unhandled floating windows as well as the sendtomouse function not getting called with a `i3run -m`

I've changed the lines to this and it has handled some of the 
`  if (floats ~ /on$/) 
    window[type][type"WF"]=1
  else
    window[type][type"WF"]=0`

**Comment by budRich** [comment]
thank you so much for these thorough issues and investigations. I made a very (i guess to large for one chunk) refactoring of the code as of the last release, and these are bugs i haven't seen or found myself yet. Your solutions (both to this and the other issue) looks right, and this one is a caused by human (me) error, the other issue, is, well ofc me as well, but more a result of the autogenerated getopts/cl-flag "system" that bashbud provides. Anyways. i will try these bugs, and fixes and will probably add them to a a bugfix release later today. I hope i3ass will improve your workflow, and if you find more issues in the future don't hesitate to  report them. These reports have been great, but you are ofc welcome to make pull requests since you also know the code and such, it is just a great way to get a good overview of the problematic line (diffs).
