### ISSUE TITLE
i3viswiz multimonitor support

### ISSUE THREAD

**Issue by indeedwatson** [budlabs/i3ass#5]
I recently got a second monitor. The i3 default focus behavior works across monitors: if I'm on the monitor on the right, on the leftmost window of that monitor, and I focus left, it will go to the monitor on the left.

i3viswiz does not do this. It would be nice if it did!

**Comment by budRich** [comment]
hello watson, sorry for the late reply. I have added some new features to viswiz, but not multimonitor support yet. the focus will instead warp. I have however a multimonitor setup at work, and i will see if i can add this feature.

**Comment by dionisiovj** [comment]
Hello, I'd like to help to implement this feature, since I also use i3viswiz.
I understand the general way it works and I think I could implement the multimonitor functionality, I'm just having a hard time understanding the way you parse the output of i3-tree (I'm not that well versed in awk). The variable names are also a bit cryptic to me (might just need to read more carefully). Do you have any commented version of the code or some progress on the feature so that I can help?
Also, wouldn't it be easier to use for example jq to parse json? Although I think you use awk just to avoid having any dependencies? jq is also very compact and has no other dependencies itself, so maybe it's worth it to have 1 dependency for readability and compactness?
Anyway, I would also implement it in awk if you prefer to stick to it :)

**Comment by uunnxx** [comment]
I'm  looking for multimonitor functionality too, because of  I didn't figure out how i3fyra works with multimonitor setup, 'cause it's not working at all...

**Comment by budRich** [comment]
@laur89 , @uunnxx 
When i did i3fyra I never intended it to be used in a multimonitor setup, since the whole thing works by figuring out if a window is at the edge of the screen or not. And i3viswiz was originally part of i3fyra, but i made it external since i thought it can be useful in workflows without i3fyra. 

But at the moment that means that i3viswiz will only be usfeful in a single monitor environment. It doesn't need to be that way and I'm sorry I haven't given this issue more attention.

This is my plan now: 
- make i3viswiz work on multimonitor setups (**without i3fyra**) as expected.
- when i3viswiz is used together with i3fyra it should take the edges of the (one) screen into account
- while doing his, annotate and make the code look better for i3viswiz (#81)

I will include that in the next i3ass update. 

However, what @uunnxx is implying, i3fyra not working on multimonitor setups. Is quite a lot more complicated. I would like this to work, but I don't think anything other then only one workspace (meaning monitor) can be a i3fyra workspace. And that can work in multimonitor setups as long as one don't try to move windows to or from that workspace with left,right,up,down movement.

I think I will make a video about this, there are so many strange edgecases, here. And it would be great to hear some ideas how this could be tackled, something tells me that there is a super simple solution to it (other then not using multiple monitors).

I would also like to add that I haven't had multiple monitors to test this myself, I do have that now, but I still only use one myself.

**Comment by kontroll** [comment]
Since the multi monitor support update I find that my bindings no longer do what I expect them to. I personally prefer my movements to be constrained to a single workspace/monitor output. So my question on this topic is whether or not it's currently (or ever going to be) possible to once again focus within those constraints?

**Comment by budRich** [comment]
@kontroll : Thank you for the question. It is a good one. Personally i never really use more then one monitor, and have only enabled multiple now when adding the new features, so i am not 100% sure how it worked before.

But i guess you mean that, now focus is moved and warped between monitors, when it previously stayed on the same monitor. I fully understand why you would prefer that behavior, but i also know that the current behavior have been requested.

I think i will try this.
There is a setting for focus_wrapping in i3. 
https://i3wm.org/docs/userguide.html#_focus_wrapping

I think i can make it so that if that setting is set to `focus_wrapping workspace` the old (the one you prefer i presume) behavior is active, otherwise, the new one will be used.

What do you think about that?

Thank you for using and testing i3ass!

**Comment by kontroll** [comment]
A setting somewhere seems like it would be a reasonable approach I hope it didn't appear as though I was saying "roll back the new stuff!" :)

**Comment by budRich** [comment]
helllo multimonitor people! all this stuff is implemented now, i hope it works fine, please let me know if it doesn't!
