### ISSUE TITLE
Scratchpads in i3fyra

### ISSUE THREAD

**Issue by fwanky** [budlabs/i3ass#65]
Is there a way to have scratchpads in i3fyra? Whenver I set a scratchpad it'll just go into whatever container I have set for my terminals, I don't see anyway around this? I know of i3run but how would I make a urxvt terminal that doesn't instantly go into the container?

Also to mention, I tried following this https://www.youtube.com/watch?v=QqDMpuIikXA;
i also tried `bindsym $mod+Shift+Return       exec i3run -i floatterm -s -e 'urxvt -name floatterm' `well as in my config but that didn't work.

**Comment by budRich** [comment]
thanks for testing i3fyra! Just as you mention, i3run is the best way to "manage scratchpads" in i3fyra, i guess what you are asking for is the window to spawn on the scratchpad. That is not a feature i have in i3run right now, but it would be easy to implement and i will try to do that for the next release. regarding "floatterm", is the problem that the window is spawned inside of a tabbed container instead of being floating? It is strongly recommended that you have a "global" for_window rule that will make all your windows floating by default, and then have rules for the ones that you want to be tiled/tabbed instead. However there are some strange stuff in i3, that will cause some minor annoyances when setting this up with a normal for_window rule in the i3 config. the currently best way is to use a subscription script and one of the ipc bindings available (i use i3ipc-python), to set this rule, i have described this whole thing in one of my later videos that i call "all my windows float" or something. One dirt hack you could do to have windows spawn on the scratch pad is to execute i3run twice on them, but this will only work properly for windows that aren't assigned to a container (A,B,C or D).

**Comment by fwanky** [comment]
Thanks for the quick response :DDDD
The issue isn't that it's not tiling or floating or such, it's that it's going into container A, rather than ignoring the i3fyra rule and floating as it's own.

**Comment by fwanky** [comment]
my bad, realised this was me using classes and not instances here. My bad brother
