### ISSUE TITLE
Newest spawned window won't take focus

### ISSUE THREAD

**Issue by ghost** [budlabs/i3ass#66]
Whenever I start a terminal, in my top container, A. It doesn't take typing focus, so i'll still be typing where I was before.

Did some testing and this only seems to be for my terminal. Urxvt..
If I start a second terminal in the same container that second terminal will take focus though./ if I start it in any other container it will take focus fine.

**Comment by budRich** [comment]
thanks for reporting this, i will look into to it. I think it's one of those issues, that i encounter myself all the time, but i have kind of gotten so used to it that i don't think about it. i am sure there is an easy fix for this, very good that you mentioned that it only happens when it's the first window in a container, helps alot.

**Comment by budRich** [comment]
i think i finally squashed this bug in the latest release.
